# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cli/core/bazel/packages_metrics/package_load_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:cli/core/bazel/packages_metrics/package_load_metrics.proto\x12#devtools.build.lib.packages.metrics\x1a\x1egoogle/protobuf/duration.proto\"\x93\x02\n\x12PackageLoadMetrics\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12>\n\rload_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationR\x0cloadDuration\x12\x1f\n\x0bnum_targets\x18\x03 \x01(\x04R\nnumTargets\x12+\n\x11\x63omputation_steps\x18\x04 \x01(\x04R\x10\x63omputationSteps\x12\x30\n\x14num_transitive_loads\x18\x05 \x01(\x04R\x12numTransitiveLoads\x12)\n\x10package_overhead\x18\x06 \x01(\x04R\x0fpackageOverhead')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cli.core.bazel.packages_metrics.package_load_metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PACKAGELOADMETRICS']._serialized_start=132
  _globals['_PACKAGELOADMETRICS']._serialized_end=407
# @@protoc_insertion_point(module_scope)
