# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cli/core/bazel/action_cache/action_cache.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.cli/core/bazel/action_cache/action_cache.proto\x12\x05\x62\x61zel\"\x9b\x04\n\x15\x41\x63tionCacheStatistics\x12\"\n\rsize_in_bytes\x18\x01 \x01(\x04R\x0bsizeInBytes\x12%\n\x0fsave_time_in_ms\x18\x02 \x01(\x04R\x0csaveTimeInMs\x12\x12\n\x04hits\x18\x03 \x01(\x05R\x04hits\x12\x16\n\x06misses\x18\x04 \x01(\x05R\x06misses\x12J\n\x0cmiss_details\x18\x05 \x03(\x0b\x32\'.bazel.ActionCacheStatistics.MissDetailR\x0bmissDetails\x12%\n\x0fload_time_in_ms\x18\x06 \x01(\x04R\x0cloadTimeInMs\x1a\x63\n\nMissDetail\x12?\n\x06reason\x18\x01 \x01(\x0e\x32\'.bazel.ActionCacheStatistics.MissReasonR\x06reason\x12\x14\n\x05\x63ount\x18\x02 \x01(\x05R\x05\x63ount\"\xb2\x01\n\nMissReason\x12\x18\n\x14\x44IFFERENT_ACTION_KEY\x10\x00\x12\x12\n\x0e\x44IFFERENT_DEPS\x10\x01\x12\x19\n\x15\x44IFFERENT_ENVIRONMENT\x10\x02\x12\x13\n\x0f\x44IFFERENT_FILES\x10\x03\x12\x19\n\x15\x43ORRUPTED_CACHE_ENTRY\x10\x04\x12\x0e\n\nNOT_CACHED\x10\x05\x12\x1b\n\x17UNCONDITIONAL_EXECUTION\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cli.core.bazel.action_cache.action_cache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTIONCACHESTATISTICS']._serialized_start=58
  _globals['_ACTIONCACHESTATISTICS']._serialized_end=597
  _globals['_ACTIONCACHESTATISTICS_MISSDETAIL']._serialized_start=317
  _globals['_ACTIONCACHESTATISTICS_MISSDETAIL']._serialized_end=416
  _globals['_ACTIONCACHESTATISTICS_MISSREASON']._serialized_start=419
  _globals['_ACTIONCACHESTATISTICS_MISSREASON']._serialized_end=597
# @@protoc_insertion_point(module_scope)
