# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cli/core/bazel/command_line/command_line.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cli.core.bazel.options import option_filters_pb2 as cli_dot_core_dot_bazel_dot_options_dot_option__filters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.cli/core/bazel/command_line/command_line.proto\x12\x0c\x63ommand_line\x1a+cli/core/bazel/options/option_filters.proto\"y\n\x0b\x43ommandLine\x12,\n\x12\x63ommand_line_label\x18\x01 \x01(\tR\x10\x63ommandLineLabel\x12<\n\x08sections\x18\x02 \x03(\x0b\x32 .command_line.CommandLineSectionR\x08sections\"\xc0\x01\n\x12\x43ommandLineSection\x12#\n\rsection_label\x18\x01 \x01(\tR\x0csectionLabel\x12\x38\n\nchunk_list\x18\x02 \x01(\x0b\x32\x17.command_line.ChunkListH\x00R\tchunkList\x12;\n\x0boption_list\x18\x03 \x01(\x0b\x32\x18.command_line.OptionListH\x00R\noptionListB\x0e\n\x0csection_type\"!\n\tChunkList\x12\x14\n\x05\x63hunk\x18\x01 \x03(\tR\x05\x63hunk\":\n\nOptionList\x12,\n\x06option\x18\x01 \x03(\x0b\x32\x14.command_line.OptionR\x06option\"\xed\x01\n\x06Option\x12#\n\rcombined_form\x18\x01 \x01(\tR\x0c\x63ombinedForm\x12\x1f\n\x0boption_name\x18\x02 \x01(\tR\noptionName\x12!\n\x0coption_value\x18\x03 \x01(\tR\x0boptionValue\x12\x39\n\x0b\x65\x66\x66\x65\x63t_tags\x18\x04 \x03(\x0e\x32\x18.options.OptionEffectTagR\neffectTags\x12?\n\rmetadata_tags\x18\x05 \x03(\x0e\x32\x1a.options.OptionMetadataTagR\x0cmetadataTagsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cli.core.bazel.command_line.command_line_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMANDLINE']._serialized_start=109
  _globals['_COMMANDLINE']._serialized_end=230
  _globals['_COMMANDLINESECTION']._serialized_start=233
  _globals['_COMMANDLINESECTION']._serialized_end=425
  _globals['_CHUNKLIST']._serialized_start=427
  _globals['_CHUNKLIST']._serialized_end=460
  _globals['_OPTIONLIST']._serialized_start=462
  _globals['_OPTIONLIST']._serialized_end=520
  _globals['_OPTION']._serialized_start=523
  _globals['_OPTION']._serialized_end=760
# @@protoc_insertion_point(module_scope)
